### PR TITLE
Open any url not assigned to a container in the default container

### PR DESCRIPTION
**Pull request by Nepherte**
This change only keeps urls explicitly assigned to a container into that container. Urls not assigned to a container will be opened into the default one (ie. 'No Container'). As such, assigning urls to 'No Container' no longer makes sense and has been removed.

### CODE REVIEW

**Comment by Nepherte** [comment]
Also related to #10.

**Comment by doronbehar** [comment]
Thanks @Nepherte, I've checked out your PR and I'm the happiest Container user ever! Since @kintesh is not responsive, and due to the fact he seem to ignore [his users' honest requests](https://github.com/kintesh/containerise/issues/10) as for this small but significant behavior change, very much like in #20, I think you should fork this addon and publish it at Mozilla's addon gallery by your self. I'd would have done so my self but I think the honor should be yours.

**Comment by doronbehar** [comment]
Thanks @kintesh , I'm sorry I've doubted your concern to your users. I can't wait to see a new release and stop use my personal fork. Thanks a lot for creating this extension in the first place :).

**Comment by kintesh** [comment]
Sorry dude. I had to find some time been very busy moving home and stuff.

**Pull request merged**
