### PR TITLE
Default containers

### LINKED ISSUE #10: Default container for opened external links
External links are now opened in the same container you were in when clicking on the link, so for example if you have Google container, sites opened from search results page end up in Google container too. Would be nice to have an option to set default container (like `No container` or `Untrusted` or random new container (like with [Click To Contain](https://addons.mozilla.org/en-US/firefox/addon/click-to-contain/) extension)).

### LINKED ISSUE #80: [feature suggestion] automaticially create & assign a container for a domain not already added
Just stumbled a cross this gem. As the subject says, if the domain isn't already added to a container, create a new container with the name of the domain and add the domain to that container.

### PR DESCRIPTION
**Pull request by LoveIsGrief**
# dev TODO

 - [x] toggable preference group  
        Visuable toggle could be done with checkbox and CSS that hides, greys out or deactivates everything in the group
 - [x] create "container name" preference
 - [x] use "container name" preference
 - [x] Allow "No Container" as container name
 - [x] use "container name" preference with variables
 - [x] use "container name" preference with `ms` variable
 - [x] "rule" preference 
 - [x] use "rule" preference 
 - [x] use "rule" preference with variables
 - [x] create "lifetime" preference (`ChoicePreference` with radio buttons)
 - [x] use "lifetime" preference: "Forever"
 - [x] use "lifetime" preference: "Until last tab is closed"
 - [x] check containers at extension startup for lifetime preference
        Those that should've been deleted, will be deleted
 - [x] Grey out preference group when not selected

# TODO future PRs

- [ ] Preference group presets

# Discussion questions:

 - [ ] How should preferences be documented without cluttering preference UI? 
   - Wiki? 
   - written in Markdown, [converted to HTML](https://www.omardelarosa.com/posts/making-a-markdown-blog-using-webpack) and opened in [an extension page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages).
   

-----

This will contain the work on default containers as well as their preferences.

It will introduce the options for default containers described in #10 and #80 (possibly other related issues if I remember/find them again).

# What is this "default container" you speak of

The container into which tabs will be placed that cannot be placed into any other container. In other words, if a tab opens or updates its URL to one that cannot be matched by a rule in the extension, it will be put into a default container according to the preferences listed below.

# Preferences

Since there have been multiple proposals on what should be done with the default container and they are at times mutually exclusive, it will be up to the user to decide. In order to do so a group of preferences related to the default container will be provided that hopefully cover the requests.

The preference group will have certain presets for the user to reach certain configuration states easily.

## Suggested preference group

The title of the group, as seen by the user, will be **Default container**. The entire group can be toggled on or off. If off, nothing will be done with unmatched URLs. Once activated the following preferences will come into effect:

**Container name** (string input)

The name the default container will possess. It will be possible to create a dynamic name using certain variables:

 - ms: current time in milliseconds
 - domain: the simple domain without the TLD or anything else
 - fqdn: [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name)
   host will work as an alias
 - tld: [TLD](https://en.wikipedia.org/wiki/Top-level_domain)

Other variables can be requested (most likely in feature requests).

Examples:

|  URL                       | containerise_{ms}          | {domain} |  {fqdn}            | default container  |
|----------------------------|----------------------------|----------|--------------------|--------------------|
|  https://example.com       | containerise_1567718601836 |  example |  example.com       | default container  |
| https://old.example.com    | containerise_1567718628706 |  example | old.example.com    |  default container |
| https://an.old.example.com | containerise_1567718738989 | example  | an.old.example.com | default container  |

**Lifetime** (choice list)

 - Forever: self-explanatory
 - Until last tab is closed: Once the last tab in the container is closed, the container will be deleted too

A possible countdown e.g "60 minutes" might be possible, but that's out of the scope of this PR.

**Rule addition** (string input)

This will create an a rule for the container. This is specifically for #80. Containers could thus be automatically created for domains.

Available variables:

 - domain: the simple domain without the TLD or anything else
 - fqdn: [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name)
 - tld: [TLD](https://en.wikipedia.org/wiki/Top-level_domain)

Examples:

|  URL                       | *.{domain}.* | *.{domain}.{tld} |  {fqdn}            |
|----------------------------|--------------|------------------|--------------------|
|  https://example.com       |  \*.example.* | *.example.com    |  example.com       |
| https://old.example.com    | \*.example.*  | *.example.com    | old.example.com    |
| https://an.old.example.com | \*.example.*  | *.example.com    | an.old.example.com |

## Suggested presets for the preference group

**"Random, temporary containers"**

By default, any unmatched URL would be put into a newly minted, unique, random container that destructs after the last tab in the container is removed.

**"Autocreate containers per domain"**

Close #80 

**"Default container"**

All unmatched URLs would end up in the same container. If I'm not mistaken this would fix #10

**"Default temporary container"**

Same as "Default container" with the change that once the last tab in the default container is closed, the default container would be closed. Fear not, the default container would be created again once an unmatched URL is encountered.

### CODE REVIEW

**Comment by LoveIsGrief** [comment]
First generation from `preferences.json` 
afbeelding

"Save" doesn't work yet, but that's coming

**Comment by NomDeMorte** [comment]
Having a single global default container carries problems of it's own. See https://github.com/kintesh/containerise/issues/53 to pick the first example I found.

For example, right now I'm logged into github with two different accounts, in two different containers. If I open an unmatched URL from this container, I'd like it to be opened in the default 'No container', but if I opened that same unmatched URL in the other container, I'd like it to remain in that same container that I'm opening it from. Same URLs in both cases, but different behaviour based on the container.

But, I notice you mention in the UI that the default container name can be a variable. Is this to allow for a future featureset where the variable is stored in the ruleset, this implementing the entry and exit rulesets [discussed here](https://github.com/kintesh/containerise/pull/20#issuecomment-493786652)?

**Comment by LoveIsGrief** [comment]
Hi @NomDeMorte 

Thank you for your response. Your focus is on entry and exit rules. I don't think default containers, as I am going to implement them, will clash with that feature request.

Since you say you're a retired dev, I think a skeleton of some python code will be simpler here (since it's closer to pseudo code). Ignore the camelcase please.

```python
def handleUrlChange(currentContainer, oldUrl, newUrl):
    
    if oldUrl.host == newUrl.host:
        return
    
    # Handle exit rules
    newContainer = currentContainer.exitRules.getContainer(newUrl)
    if newContainer:
        return createTab(newUrl)
    
    # Handle entry rules
    newContainer = getContainer(newUrl)
    if newContainer:
        return createTab(newUrl)
    
    # Default container being implemented
    newContainer = getDefaultContainer(newUrl)
    if newContainer:
        return createTab(newUrl)
    
    # Default container not activated.
    # Nothing to do
```

I can ping you once I have implemented `getDefaultContainer` then you'll understand what the naming will do from the  code. All it does is generate a name for the container. If you look at the examples in my first comment, you should get an idea.

**Comment by LoveIsGrief** [comment]
[Example of `{host}` container name](https://streamable.com/bvpwn)

**Comment by NomDeMorte** [comment]
> Your focus is on entry and exit rules.

So is yours :) A global default container is a global exit rule. 

If I'm understanding your pseudocode correctly, `getDefaultContainer(newUrl)` could just call `.exitRules.getContainer(newUrl)`, where `.getContainer()` (the container class's member function) handles unmatched URLs - as should `getContainer()` (the global function) .... That being the case, there is no need for `getDefaultContainer()` to exist really.

It will be good if your implementation doesn't directly block future feature requests... but it would also be a shame for your work to have to be removed and replaced with something else, in order to meet those requests, when the same amount of your work could instead apply some feature requests now (ie global exit rules), and have half of the work done for other feature requests (ie per-container exit rules).

I just want to make sure you are getting the best return on your investment of time, and also allowing future work to benefit from that investment.

**Comment by LoveIsGrief** [comment]
[Video of current dev status](https://streamable.com/bzs2q)

@NomDeMorte I disagree on where `getDefaultContainer` should reside. I believe it should stay global. Container exit rules can come in another PR, but they shouldn't be handling global issues only their own. Default containers are a global fallback, not a per container fallback.

This PR is already big enough as it is. Adding exit rules would make it enormous and I'd rather separate concerns.

**Comment by LoveIsGrief** [comment]
[Current dev status](https://streamable.com/7xcg9)

Only have problems with the `ms` variable which would make true, random, default containers possible.

**Comment by LoveIsGrief** [comment]
[Final feature: random, default containers](https://streamable.com/ck6a8)

**Comment by NomDeMorte** [comment]
> I disagree on where `getDefaultContainer `should reside.

As I explained above, it does not need to exist at all, it is redundant, because getContainer() can, and should, handle it.
That redundancy is the reason for this duplicated code:

```
    # Handle entry rules
    newContainer = getContainer(newUrl)
    if newContainer:
        return createTab(newUrl, newContainer)
    
    # Default container being implemented
    newContainer = getDefaultContainer(newUrl)
    if newContainer:
        return createTab(newUrl, newContainer)
```


> Default containers are a global fallback, not a per container fallback.

That's precisely the problem. A global implementation cannot handle containers (because it is not container-aware). A per-container implementation can do both (by disregarding its own container-awareness)

If you only consider a global implementation, then it can cause you can make code which makes it harder to implement a per-container handler. If you consider both global and per-container handlers, then you can create code which allows you to do part of the work (global handler) now, and for someone else to efficiently do the rest of the job (per-container handlers) later.


> I'd rather separate concerns.

That's unfortunate because they are not separate concerns. They are the same - "What should it do when we click an unmatched URL". For some people, the answer is "It should globally do <something>", but for some users, the answer is "It should do <something> depending on which container I'm coming from."


> This PR is already big enough as it is. Adding exit rules would make it enormous 

I'm not suggesting you fully implement per-container exit rules in this one PR. What I am pointing out, is that the most efficient way to implement both, is to consider both, and recognise that a global handler which this PR will implement, is only a small part of a bigger problem which is container-variant.

The path you are on now:
Create global handler, which does not perform differently per-container <-- You stop here
Remove global handler <-- Someone does this later. RIP your work, now wasted.
Create per container handler <-- So they can do this. More work for them.

The path you could be on:
Create per container handler, which does not perform differently per-container <-- You stop here
Modify existing handler to act differently per-container <-- Someone does this later. Less work for them.


It's obvious which one is more enormous in the long-term.

**Comment by LoveIsGrief** [comment]
@NomDeMorte feel free to fork my repo and make the changes you think are necessary.

**Comment by NomDeMorte** [comment]
> @NomDeMorte feel free to fork my repo and make the changes you think are necessary.

That does not solve the problem I'm observing, it is the problem I'm observing. No need to write code which needs to be changed, just write it once in a way that does not require the changes.

**Comment by LoveIsGrief** [comment]
Alright, I'm submitting it like this. The rest can be done in other PRs.

@kintesh when you find the time, I look forward to a code review.

**Comment by kristofferR** [comment]
Thanks for this @LoveIsGrief, awesome work. Containers are finally useful for their purpose of containing.

However, some problems remain. I tested your PR and an issue is that external links (going from special container->default container) behaves irradically. External links that open a new tab exit the container while external links that open in the same tab doesn't exit the container. 

I'm fine with that behavior, as it keeps the backward history intact, but for other people a preference would likely be preferred. Some people will likely prefer their containers to be clean, regardless of weather a link contains a target="_blank" or not.

Another issue is that the opened extenal links aren't counted as child tabs in [Tree Style Tabs](https://github.com/piroor/treestyletab). It seems pretty simple to fix, you just need to specify the `openerTabId` option: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-child-tab-from-a-specific-tab

**Comment by LoveIsGrief** [comment]
> I tested your PR and an issue is that external links (going from special container->default container) behaves irradically.

Erratically? How so?

> External links that open a new tab exit the container while external links that open in the same tab doesn't exit the container.

Could you describe a scenario or record it? I need more information to reproduce what you're observing in order to correct it.

> Some people will likely prefer their containers to be clean, regardless of weather a link contains a target="_blank" or not.

Doesn't defining the name of containers using the `{ms}` variable help? [See the video](https://streamable.com/ck6a8) I made a day or so ago. If that isn't what you're looking for, please describe a step by step scenario and what you expect to happen.

> Another issue is that the opened external links aren't counted as child tabs in Tree Style Tabs. It seems pretty simple to fix, you just need to specify the openerTabId option: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-child-tab-from-a-specific-tab

The `openerTabId` is passed [here](https://github.com/kintesh/containerise/pull/91/files#diff-d1e8ddf75413494c662fa96c6368c790R84). I too use TST and tested the extension and this pullrequest with it 🤔 What are you observing?

**Comment by kristofferR** [comment]
Haha, I figured it out. Due to a settings layout bug I completely overlooked the Save button, so I didn't really test your PR.

Skjermbilde 2019-09-13 kl  12 58 39

I've actually tested your PR now, and it works as designed as far as I can see. However, what I really want is to use the default "no container"-container as the default container. For several reasons - vertical space in the toolbar is at a huge premium on my laptop, and there's no point of marking/color coding almost everything as the default. 

Is that possible right now or still unimplemented?

**Comment by LoveIsGrief** [comment]
I just really suck at design and layout @kristofferR 😆 Dunno where to put the save button make it obvious or which color to give it.

As for a using "No container" as a default, I have seen people using `@.*` as a rule there, so you can already do that today.

You did avert me to using "No container"  in Default Container > Container name that wouldn't work. Then you would be able to use this feature for that purpose too.

**Comment by kristofferR** [comment]
If you want to keep the save button on the side, it should at least be four times as wide. The "Save" text should also be horizontal, vertical text like now is almost never a good idea.

I still can't get the child tab functionality to work right. If you want to keep the save button on the side, it should at least be four times as wide. The "Save" text should also be horizontal, vertical text like now is almost never a good idea.

I still can't get the child tab functionality to work right. Tabs simply open in a new mother tab.

I've also opened up a new, quite related, issue (#93) about how the "Keep old tabs" works.

**Comment by LoveIsGrief** [comment]
@kristofferR could you record what's going wrong with TST? [These are my results](https://streamable.com/cql29)

I'll modify the button next week, when I have time. Thanks for the feedback!

**Comment by kristofferR** [comment]
https://streamable.com/0etkx

As you can see, the links I click doesn't open in child tabs.

**Comment by LoveIsGrief** [comment]
Cheers. I'll try to recreate it.

**Comment by crssi** [comment]
What about save on change and no button at all?

Cheers

**Comment by LoveIsGrief** [comment]
I think I'll go for the  "save on change". It might be more intuitive indeed

**Comment by NomDeMorte** [comment]
Save on change is bad because if a user clicks something in error it's done. That's why Save/apply/close/etc buttons are standard.

**Comment by kristofferR** [comment]
Thanks for implementing support for No container, but unfortunately it's really wonky. It seems to still use the container functionality despite it's not being needed. The pages are quickly closed and reloaded, and the back button/history doesn't work at all. 

Would it be possible for it to instead completely bypass the container functionality so that pages that open without a container function as normal?

**Comment by LoveIsGrief** [comment]
@kristofferR It should work now.

**Comment by NomDeMorte** [comment]
> Save on change is bad because if a user clicks something in error it's done. That's why Save/apply/close/etc buttons are standard.

And thumbs down for having a brain and learning from the mistakes of the past..... You people never learn. This entire commit is evidence of that.

I'm done here. Dig your own holes.

**Comment by sungerbob** [comment]
Hey, out of context but I want to try this. Can you publish compiled version of this branch? I want to use it.
Thank you.

**Comment by LoveIsGrief** [comment]
@sungerbob this is the one I'm currently using [containerise-3.5.3alpha.zip](https://ipfsbrowser.com/?hash=QmNN5QorvutAwSH2QwY8yU3ieSWhSHwcnkyQK4K3WPHQ7a). I uploaded it to IPFS. If it goes down I'll find another host.

**Pull request merged**
