### PR TITLE
persist active tabs

### PR DESCRIPTION
**Pull request by andreicristianpetcu**
Fixes this issue https://github.com/kintesh/containerise/issues/28

### CODE REVIEW

**Comment by ethhics** [comment]
Additionally fixes #12, #14, and #26

**Comment by andreicristianpetcu** [comment]
I had no clue there were so many related issues :) It took me more to report the bug than to fix it :)

**Comment by andreicristianpetcu** [comment]
@kintesh can you please look into this PR? There are just 3 lines changed, the rest is indentation.

**Comment by kintesh** [comment]
I will look at it soon.

**Pull request merged**
