### PR TITLE
Remove old entries from the DB upon modification

### PR DESCRIPTION
**Pull request by LoveIsGrief**
Store the host value in the HTMLInputElement for later use

We can then detect differences between what the user entered and
 what was in the DB to decide which host values to remove from our maps.

Related to kintesh/containerise#45 Updating entries leaves the old entry and creates a new one

### CODE REVIEW

**Comment by kintesh** [comment]
No longer needed. Thanks for quick fix.

**Comment by LoveIsGrief** [comment]
@kintesh this wasn't for fixing the issues of version 3.1.0 It's for #45 

which is this issue:
before

This PR fixes it

**Comment by LoveIsGrief** [comment]
@kintesh could you please have a new look at this? The issue persists and this fix wasn't merged

**Comment by LoveIsGrief** [comment]
@kintesh, do you mind if I reopen this? #45 is still an issue

**Pull request closed without merging**
